
HOST, PORT1, PORT2 = "localhost", 9998, 9999
SHARED_FOLDER = "../shared/"
SEED_ENTROPY = 123
NAIVE_PIR_NUM_DOCS = 10
DOCS_PATH = "../Gutenberg/txt/"
SCORES_HEADER = b"SCORES"
PIR_HEADER = b"PIR"
DOCS_DELIM = ';;;;;'
